### ISSUE TITLE
New Icon And Google Play Feature Graphic

### ISSUE THREAD

**Issue by DavidXochipilli** [brarcher/loyalty-card-locker#151]
Are you interested in a new launcher icon and [Google Play](https://play.google.com/store/apps/details?id=borsh.diploma_chinese_checkers) feature graphic?

**Comment by brarcher** [comment]
You are welcome to propose some new graphics, let me know what you are thinking. Certainly the feature graphic is hobbled together and could be improved. (:

**Comment by DavidXochipilli** [comment]
What do you think of this one?

![material_design_icon](https://user-images.githubusercontent.com/29784866/32912895-c9d974fa-cb10-11e7-8678-aed30ed4ce1f.png)

The icon is under the CC0 1.0 Universal license.

**Comment by brarcher** [comment]
The logo looks nice. If it is the logo for the Loyalty Card application it may not clearly show what the application does, though. Maybe I am overly practical and literal, but the logo presently may give a better idea of what the app is for. The logo you have created reminds me of a gift card. Would you be interested in contributing this to another application I have which related to gift cards: [gift-card-guard](https://github.com/brarcher/gift-card-guard)?

**Comment by DavidXochipilli** [comment]
Thanks for your review @brarcher. As suggested, I made a comment [there](https://github.com/brarcher/gift-card-guard/issues/28) and will try another design here later this year.

**Comment by DavidXochipilli** [comment]
Here is another try:

![loyalty-card-locker](https://user-images.githubusercontent.com/29784866/33741995-c009fc64-dba6-11e7-939e-e60f5366ff52.png)

I will make another icon with a VIP customer carrying bags and a crown on his head.

What do you think? Did you come up with any ideas?

**Comment by brarcher** [comment]
The stacking of cards is good, it shows that there could be multiple items managed by the app.

I'd be interested to see if the cards themselves could represent a store loyalty card. The card from this graphic looks much like a gift card because of the ribbon. The cards look nice, but it may be a little confusing.

The crown or a customer carry bags may work. Another idea may be an generic image of a store front or something that represents a business. I looked at a [company that prints loyalty cards](https://www.plasticresource.com/plastic/loyalty-cards.html) for some ideas, but their examples really are a company name and logo, which it is hard to make a "generic card" from.

One other idea to play with would be the card shapes themselves. From what I have experienced there are two formats for loyalty cards: the full "credit-card" sized cards that go in one's wallet or a keyring card. How might several keyring shaped cards appear using this pattern? Or maybe using that shape given the side of the icon may end up looking a little narrow or too busy, not sure.

Another approach would be to show something more literal. As an example, the [zxing barcode scanner app](https://play.google.com/store/apps/details?id=com.google.zxing.client.android) has the following icon:

![image](https://user-images.githubusercontent.com/5264535/33748193-1868c258-db95-11e7-9911-5eb36a0ca95c.png)

But, again, maybe that is too busy or too literal.

**Comment by DavidXochipilli** [comment]
What do you think of this approach?

![materialdesign_side](https://user-images.githubusercontent.com/29784866/34320371-11e1987c-e7f9-11e7-96c2-563fda533bc0.png)

**Comment by DavidXochipilli** [comment]
By the way, I wish all of you a Merry Christmas and a wonderful New Year!

![mc](https://user-images.githubusercontent.com/29784866/34320380-7315a1a6-e7f9-11e7-8bb9-27abbf0ba8c4.gif)

**Comment by brarcher** [comment]
I think that this approach is getting closer. It looks more like a loyalty card rather than a gift card.

Does the icon need to fit the color scheme of the rest of the app, or is it common for the icon to use different colors?

I would like to get the opinion of @betsythefc to see what he thinks, as he is the creator of the existing icon.

**Comment by betsythefc** [comment]
It's definitely a lot prettier than mine is. I do think that the icon should match the color scheme of the app (or vice versa).

If this icon is adopted, I'd say the top bar of the app should become the primary blue of this icon.

**Comment by DavidXochipilli** [comment]
Do you have any ideas how I could change the icon or an exact imagination for a new one? I am out of ideas for the time being. 😅

Regarding the color scheme, I think the same like @betsythefc. But I can change the colors if you prefer something else @brarcher.

Can I process with sending you a .zip with the needed icon sizes and source file?

**Comment by brarcher** [comment]
I think that the icon is good as is. Really, I was hoping to get the opinion of @betsythefc, so that if the icon was changed he would not be surprised. It sounds like he is OK of the new icon, so lets go forward with it. Thanks for your hard work!

Please attach a zip file with the png's for the icons, as well as the source file. I'll coordinate a change to update the colors used in the app to match the icon. To be clear, though, the "top bar" of the app is the one with the title:

![image](https://user-images.githubusercontent.com/5264535/34423156-2dfdb980-ebe8-11e7-8fda-ac62217e3eba.png)

Or is it the status bar, which is a darker gray:

![image](https://user-images.githubusercontent.com/5264535/34423176-54693e28-ebe8-11e7-8cf2-c904fa52dcb8.png)

Or, should both of these be updated? If they both should be updated, can I get a suggestion for what colors each should be, preferably HTML encoded?

**Comment by brarcher** [comment]
So it is easier, the icon sizes that I'll need are:

app icon:
48 × 48
72 × 72
96 × 96
144 × 144
192 × 192

used in first start wizard:
192 × 192 
288 × 288
384 × 384
576 × 576
768 × 768

Play store:
512 x 512 [32-bit PNG (with alpha)]

If you are interested in making a feature graphic (similar to that for the gift card app earlier), that is:
1024 w x 500 h
JPG or 24-bit PNG (no alpha)

The current graphic looks like this:

<img width="303" alt="screen shot 2017-12-28 at 4 11 05 pm" src="https://user-images.githubusercontent.com/5264535/34423408-c54b72f4-ebe9-11e7-8b88-c4934c628b64.png">

Thanks!

**Comment by DavidXochipilli** [comment]
I attached the zip with the icon and the needed sizes. I will send you the images for the first start wizard and a Google Play feature graphic later this month.

Regarding the colors, I suggest Indigo for the top bar and Indigo 700 for the status bar and amber for selector/selection.
https://material.io/color/#!/?view.left=0&view.right=0&primary.color=3F51B5&secondary.color=FFC107

[loyalty-card-locker_icon.zip](https://github.com/brarcher/loyalty-card-locker/files/1596388/loyalty-card-locker_icon.zip)

**Comment by brarcher** [comment]
I like the suggested color scheme. I'll make that change as well.

Are these graphic provided under CC0 1.0 Universal license, like the Gift Card app, and should samymarboy be mentioned in the commit?

**Comment by DavidXochipilli** [comment]
Yes, these graphics are under the CC0 1.0 Universal license and credits go to @samymarboy again 👍🏻 
Please find the onboarding graphics enclosed. 


[Onboarding.zip](https://github.com/brarcher/loyalty-card-locker/files/1598926/Onboarding.zip)

**Comment by brarcher** [comment]
The changes with the new icon have been committed. I'll try to create a new release some time this week and update the icon on the Play store. When you have time to create a replacement feature graphic let me know and I'll change it in the Play store.

It is looking good. Thanks!

**Comment by DavidXochipilli** [comment]
Thanks @brarcher. I will drop a line here when I finished the Google Play feature graphic.

**Comment by brarcher** [comment]
FYI @DavidXochipilli , I received some good feedback on the new logo and color scheme from users on Google Play. Users like it! (:

**Comment by DavidXochipilli** [comment]
That makes me happy! 🤩

What do you think of that feature graphic for Google Play?

![googleplayfeaturegraphic](https://user-images.githubusercontent.com/29784866/36056516-5b1bbf36-0e05-11e8-9685-305432ee1ead.png)

**Comment by betsythefc** [comment]
I love that feature graphic. I think it does a great job matching the icon!

**Comment by brarcher** [comment]
I like it!

It has been added to Google Play. Look forward to seeing it up soon. (:   Thanks!
