### ISSUE TITLE
Import not working properly

### ISSUE THREAD

**Issue by airon90** [brarcher/loyalty-card-locker#152]
I'm using latest version of this app from F-Droid on Android 7.1.2 and it cannot import a backup file from filesystem

**Comment by brarcher** [comment]
Running with Android 7.1.2 using LineageOS I find that the external application defaults to the storage manager. The file to import is being provided as a content URI, and Budget Watch cannot handle that. Instead, the logs report:
``11-12 21:20:44.974  1757  1757 E BudgetWatch: Starting file import with: content://com.android.providers.downloads.documents/document/423
11-12 21:20:44.974  1757  1757 D BudgetWatch: Attempting to determine file type for: 423
11-12 21:20:44.975  1757  1757 W BudgetWatch: Could not import /document/423, could not determine extension
```
and the following message is reported on the screen:
```
Import failed
Failed to import: /document/423
```

Is this similar to what you observed? If so, it appears that support for importing files as a content URI will need to be added.

**Comment by airon90** [comment]
I don't know how to send you a log file. I just can say that when you press the button "Import from filesystem" the app crashes

**Comment by brarcher** [comment]
I'll look into a fix for this. If you need to import your data in the meantime, the last import option "Import from export location" will look for a file at a specific location. If you export the current config, it will mention where that is. If you copy your backup to that file and use the last import option you should be able to successfully import.

If you are up for getting logs (in case what I see is not what you see), try the following:
1) Enable developer mode through Settings: [instructions](https://developer.android.com/studio/debug/dev-options.html)
2) Go to the developer options in settings: Settings -> System -> Developer Options
3) Near the top of the developer options is an option to "Take bug report". That will gather logs and other information. Do this after reproducing the issue.
4) You can email me the bug report (instead of posting it here), or you can get the logs from the report and post them here or email them to me. The logs are located in the report's zip file. There will be a file called something like this: bugreport-NJH47F-2017-11-13-07-34-09.txt. 

If you are not up for gathering the logs, you can check that it does resolve what you see when I create a fix.

**Comment by airon90** [comment]
[bugreport-N2G47H-2017-11-14-14-41-56.txt](https://github.com/brarcher/loyalty-card-locker/files/1474603/bugreport-N2G47H-2017-11-14-14-41-56.txt)

I hope it will be useful :)

**Comment by brarcher** [comment]
Thanks for posting the logs. The issue you are observing is related to the issue I've reproduced locally. I believe that starting in Android 7 applications need to provide files via content providers instead of direct file URIs. This application does not yet do that, as the following stack trace from your logs show:
```
11-14 14:39:20.096  7220  7220 E AndroidRuntime: FATAL EXCEPTION: main
11-14 14:39:20.096  7220  7220 E AndroidRuntime: Process: protect.card_locker, PID: 7220
11-14 14:39:20.096  7220  7220 E AndroidRuntime: android.os.FileUriExposedException: file:// exposed beyond app through Intent.getData()
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1800)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.net.Uri.checkFileUriExposed(Uri.java:2346)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:8988)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.content.Intent.prepareToLeaveProcess(Intent.java:8949)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4288)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4246)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at protect.card_locker.ImportExportActivity.chooseFileWithIntent(ImportExportActivity.java:334)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at protect.card_locker.ImportExportActivity.access$100(ImportExportActivity.java:29)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at protect.card_locker.ImportExportActivity$2.onClick(ImportExportActivity.java:90)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.view.View.performClick(View.java:5665)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:22864)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.os.Looper.TinnoLoop(Looper.java:150)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:208)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6175)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
11-14 14:39:20.096  7220  7220 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```
I'll look generally using content providers for importing and exporting.

**Comment by airon90** [comment]
By now I imported the backup as you suggested :)
Thank you for your work!

**Comment by brarcher** [comment]
This should be resolved now. If it does not work in the next release, please re-open.
