### ISSUE TITLE
Please remove shortcut permission

### ISSUE THREAD

**Issue by CyrusCT** [brarcher/loyalty-card-locker#162]
Version 0.15 adds a permission for the app to add shortcuts.  The permissions-friendly approach is for shortcuts to be made through a launcher instead of the app.  My security software flags the install shortcuts permission as a potentially malicious risk.  Please remove to restore Loyalty Card Keychain's status as a permissions-friendly app.

**Comment by brarcher** [comment]
Thanks for the feedback. From comments from other users I investigated the adding of proper shortcuts, which is released in v0.15. Since then I have also added support for creating shortcuts from the Launcher (https://github.com/brarcher/loyalty-card-locker/pull/161). As adding them from the launcher is probably the better way to go, I've been on the fence about removing the ability to add shortcuts from the app. I'm OK with removing the ability, but could you also provide for my reference some supporting documentation as to why it may be a malicious risk? Is the concern that an app could install a shortcut which masquerades as another app?

**Comment by brarcher** [comment]
The shortcut permission will be removed in the next version of the app. If you have any other feedback, please let me know.

**Comment by CyrusCT** [comment]
Other feedback:  Love the app! Love that it's permissions-friendly.  Being able to type-in the number for a barcode was a huge plus because I had some loyalty cards with too much wear & tear to capture otherwise.  The app is very intuitive.  The auto-brightness adjustment is very helpful with certain retailers, and I often get a better scan than with the original card.  Some cards have much more detail than the barcode, and having the notes display above the code helps with cards that use additional authentication factors.  
--

**Comment by brarcher** [comment]
I happy to hear that the app is useful. (: 

If you think of future suggestions for the app, just let me know.
