### ISSUE TITLE
Unreadable generated barcode

### ISSUE THREAD

**Issue by Almtesh** [brarcher/loyalty-card-locker#17]
The cards' barcodes shown by the app are too small to be read by a barcode scanner, that would be great to print them in a greater size or show them in fullscreen, and perhaps in landscape by default when you click on the little barcode.

**Comment by brarcher** [comment]
You are right. Some of the displayed barcodes types are too small to be practical. Sorry about that. I've added a change [here](https://github.com/brarcher/loyalty-card-locker/pull/13) which should hopefully address that. If you are able, you can give the latest master branch a try and see if it resolves your concern. Otherwise, the next release on F-Droid should contain a fix.

**Comment by Almtesh** [comment]
I don't have anything to get your fixed version, so I will wait for the F-droid version and give you my opinion on it.

**Comment by brarcher** [comment]
No problem. A release has been cut, and should be picked up by F-Droid in the next day or so.

**Comment by Almtesh** [comment]
That looks good, closing issue.
