### ISSUE TITLE
qr model 1

### ISSUE THREAD

**Issue by Rsathishkumar87** [brarcher/loyalty-card-locker#306]

**Comment by brarcher** [comment]
The app supports a type of QR code. Is it Model 2? The support for QR codes is due to the [ZXing](https://github.com/zxing/zxing) library. If you are interested in having support for QR Model 1 ZXing will need to provide support. However, ZXing is in maintenance mode and has no roadmap for new features. I do not see QR Model 1 being supported. If that changes, feel free to re-open this.
