### ISSUE TITLE
Add to play store

### ISSUE THREAD

**Issue by nkour** [brarcher/loyalty-card-locker#32]
Unless I am mistaken you have the only open source app for this thing. OK I got fdroid but for better exposure why not add it to play store?

**Comment by Vebryn** [comment]
I totally agree :+1:

**Comment by brarcher** [comment]
I may consider it a little later. There are a few features and/or bugs which I would like to add before moving to the Play store. Also, I would need to [pay $25](https://play.google.com/apps/publish/signup/) for the privilege of adding my open source app to the Play store. I'll need to get over that as well. F-Droid is free. (:

**Comment by Vebryn** [comment]
Hello,

Thanks for your answer!

You may add a donation feature on the Github page? Or put a price of 0,79€ on the Play store?

Are updates free of charge on Play store?

**Comment by brarcher** [comment]
I think that the developer registration for the Play store costs $25, but it appears that is the only charge. So, it would be a one-time $25 charge.

> You may add a donation feature on the Github page? Or put a price of 0,79€ on the Play store?

Nah, I'm not looking to make any money on it. (:

**Comment by Airon90** [comment]
Instead of Google Play Store, what about Aptoide? It seems to be free and to be open source itself too
http://www.aptoide.com/page/publishers

**Comment by denilsonsa** [comment]
I know this was closed one year ago… But I'd like to see this app on the Google Play Store. Why? Because I want to suggest it to some friends, and I don't want explain them how to use fdroid or manually install apps.

I think this app is unique because it's the only one I found that is open-source, that does only one thing and does it well, and that doesn't send my data to external services.

If the only obstacle is the $25 fee, I can help contributing some money to help you pay it. AFAIK, that's a one-time fee, just like in Chrome Web Store (that I paid long time ago to publish an open-source chrome extension I wrote).

**Comment by brarcher** [comment]
I feel that enough people have asked that maybe I should put it on the play store. (:

I'll make it a point to look into it over the next month and get it on the play store.

**Comment by betsythefc** [comment]
@brarcher 
Do you have the photo editing software gimp? In the root of the repo there is the file `ic_launcher.xcf` which is the gimp file of the icon. This is natively 512x512 and can be exported to png from gimp. If you don't have gimp, it is F/OSS (free to download). I can also create a pull request with the exported png in the root of the repo.

**Comment by brarcher** [comment]
Oh, I did not realize that! I'll use gimp to export it into a png file. I'll also create a quick image for the feature graphic using the large icon. You are more than welcome to suggest something better, if you would like. (:

**Comment by betsythefc** [comment]
I have a basic idea for the feature picture. I can make a mockup on Sunday and share it here for approval 😃

**Comment by brarcher** [comment]
That sounds great!

**Comment by brarcher** [comment]
With the information that I have now, I was able to push v0.10 to the Google Play Store. It is currently pending release. Perhaps it will finish in a few days and be available.

@betsythefc When a feature picture is finalized I can update it on the Play Store. I'm not that concerned in the mean time that it will be featured.

**Comment by brarcher** [comment]
The application has been accepted into the Google Play Store: https://play.google.com/store/apps/details?id=protect.card_locker

**Comment by brarcher** [comment]
I have the application loaded on the Google Play store and all is well. Because it went well, I decided to upload several of my other applications, namely [Budget Watch](https://github.com/brarcher/budget-watch) and [Baby Sleep Sounds](https://github.com/brarcher/baby-sleep-sounds). Would you guess that the applications have already been uploaded ([Budget Watch](https://play.google.com/store/apps/details?id=protect.budgetwatch), [Baby Sleep Sounds](https://play.google.com/store/apps/details?id=protect.babysleepsounds)), using the same applicationId, and neither 'author' links back to source as is required by GPLv3!

**Comment by brarcher** [comment]
This application is now in the play store, as requested.
