### ISSUE TITLE
barcode not beeing scanned

### ISSUE THREAD

**Issue by nkour** [brarcher/loyalty-card-locker#33]
![20160421_161843](https://cloud.githubusercontent.com/assets/4855416/14734546/bf5a3f48-0873-11e6-9d6e-366a45320fc2.jpg)

tried to scan two times, nothing happened

**Comment by brarcher** [comment]
This appears to be an EAN-8 barcode:

![image](https://cloud.githubusercontent.com/assets/5264535/14954055/128752f2-103d-11e6-8acf-ea26d3dfb290.png)

I confirm that I am not able to capture the barcode from your picture, but a clearer barcode (included above) does capture.

It is not clear from the picture, but are the white bars near the first part of the barcode really faint in reality?

![screen shot 2016-05-02 at 8 10 05 am](https://cloud.githubusercontent.com/assets/5264535/14954090/67ce3f28-103d-11e6-8b73-cc9978d044d4.png)

I wonder if the barcode library the application is using is not able to read the barcode because it is not clear enough. I'll see if there is an update to the [zxing](https://github.com/zxing/zxing/releases) barcode library which may resolve this.

**Comment by brarcher** [comment]
Unfortunately, the zxing library being used is the latest available from the [jcenter](https://jcenter.bintray.com/com/google/zxing/core/) repository.

If you are able to get a clear image of the barcode, perhaps by putting it on a scanner and getting a copy, perhaps you may be interested in [opening an issue with zxing](https://github.com/zxing/zxing/issues) and reporting the barcode as unexpectedly unreadable. Short of that, there is nothing that the Loyalty Card Locker application will be able to do in order to compensate.

**Comment by brarcher** [comment]
As of v0.6 one may manually add a barcode. This should help get around cases where the barcode itself cannot be recognized. As the barcode recognition issue is with the zxing library, there is nothing further which can be done in this application.
