### ISSUE TITLE
[Feature request] Add support for Aztec Code

### ISSUE THREAD

**Issue by dmlemos** [brarcher/loyalty-card-locker#365]
I am from the UK. Tesco cards have started to use this type. Would be great if support could be added.

Much prefer using this app than other non open-source apps.

Alternatively #366

**Comment by TheLastProject** [comment]
AZTEC should be supported: https://github.com/brarcher/loyalty-card-locker/blob/678f12640300f9325f7ac869ab6862261b6672dc/app/src/main/java/protect/card_locker/BarcodeSelectorActivity.java#L48-L61

Are you sure you don't just have issues scanning the card due to bad light conditions or shadow over the code or something like that?

**Comment by dmlemos** [comment]
@TheLastProject you're right actually. I scanned the card using another app in the exact same spot.
After moving to another spot it took a bit more time, but it worked. Apologies for wasting your time.

**Comment by TheLastProject** [comment]
Not a waste of time, worst case scenario someone else will see this issue :)
