### ISSUE TITLE
Resizing Using nearest neighbour causes barcodes to be come blury

### ISSUE THREAD

**Issue by ioangogo** [brarcher/loyalty-card-locker#37]
Due to the resizing method that android uses on barcodes in this app, the barcodes become blury and do not look nice. This problem does not effect image scanning through zxings barcode scanner, but I have not tested it in the shops that use these barcodes. This issue may only be aesthetic.
![screenshot_2016-05-12-15-23-02](https://cloud.githubusercontent.com/assets/7449028/15218086/3210ceac-1856-11e6-9503-9ad8ebec75ec.png)

**Comment by ioangogo** [comment]
I had found some ways of solving it, but they do not currently work in the implementation of this activity

**Comment by brarcher** [comment]
I'll agree that the generation and displaying of the barcodes can be more robust. What are the ways you have found which may resolve this? If you have some ideas, feel free to create a pull request.

**Comment by brarcher** [comment]
It turns out that the library used to create datamatrix barcodes returns the smallest image necessary to contain the barcode. Android then scales this using [bi-linear filtering](https://en.wikipedia.org/wiki/Bilinear_filtering). The result is a blurry barcode:

![screenshot_2016-05-21-18-10-43](https://cloud.githubusercontent.com/assets/5264535/15451082/161f4c06-1f80-11e6-8640-85de1c105ec5.png)

It turns out that one can scale a barcode without using this filter. 

![screenshot_2016-05-21-18-14-23](https://cloud.githubusercontent.com/assets/5264535/15451081/02d17b24-1f80-11e6-9c3d-652716efb604.png)

I'll put this change in.

**Comment by brarcher** [comment]
This should be resolved in v0.6. If it is not, please re-open this issue.
