### ISSUE TITLE
An interface button to max out the screen backlighting

### ISSUE THREAD

**Issue by bracuphoth** [brarcher/loyalty-card-locker#68]
Most barcode readers available in stores simply can't read the barcode at the backlighting levels I use the phone. So I have to go into the menu, max out the backlighting, scan the barcode and go back and adjust the light to a somewhat close value to what was before. Can you do a button for the interface that once pushed when the entry is opened, say next to the pencil for editing the entry, will save the backlighting value, max it up and when pushed again will restore the backlighting intensity value from before?

**Comment by brarcher** [comment]
Another user logged the following issue (https://github.com/brarcher/loyalty-card-locker/issues/21) about maximizing the brightness. In response I added a change which will increase the brightness of the screen to its maximum while viewing a barcode. I do not believe that the change has made it into a release yet. I'll create a release so that the change can be picked up.

**Comment by brarcher** [comment]
I've created release [v0.8](https://github.com/brarcher/loyalty-card-locker/releases/tag/v0.8), which has the mentioned change. That should make it to F-Droid in a day or two. If in that release you do not find the issue resolved, let me know and the issue will be reopened.

**Comment by bracuphoth** [comment]
Thank you. And sorry for not checking the already posted request. Once the f-droid upgrades I will come with feed-back.

**Comment by bracuphoth** [comment]
In my case it works. Thank you. I still think a on/off or pushed/not pushed button would come in handy. But the fix works.
